Blogat/Models/Message/MessageModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Blogat.Models.Message
{
	public class MessageModel
	{
		public int Id { get; set; }
		public string Email { get; set; }
		public string Name { get; set; }
		public string Tel { get; set; }
		public string Text { get; set; }
		public DateTime SubmittedAt { get; set; }
	}
}

Blogat/Models/Message/MessageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Blogat.Models.Message
{
	public class MessageViewModel
	{
		public List<MessageModel> Messages { get; set; }
	}
}

Blogat/Controllers/ExportController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL;
using OfficeOpenXml;
namespace Blogat.Controllers
{
    public class ExportController : BaseController
    {
        // GET: Export
        public FileResult AllMessages()
        {
			IEnumerable<Message> dalMessages;
			MemoryStream stream;
			using (Context)
			{
				dalMessages = Context.MessageRepository.GetAll();

				using (var p = new ExcelPackage())
				{

					var ws = p.Workbook.Worksheets.Add("User messages");
					int row = 1, col = 1;

					ws.Cells[row, col].Value = "Id";
					ws.Cells[row, col + 1].Value = "Email";
					ws.Cells[row, col + 2].Value = "Nick";
					ws.Cells[row, col + 3].Value = "Phone No.";
					ws.Cells[row, col + 4].Value = "Message";
					ws.Cells[row, col + 5].Value = "Submitted at";
					row++;
					foreach (var message in dalMessages)
					{
						ws.Cells[row, col].Value = message.Id;
						ws.Cells[row, col + 1].Value = message.Email;
						if (message.UserId == null)
						{
							ws.Cells[row, col + 2].Value = message.Name;
						}
						else
						{
							ws.Cells[row, col + 2].Value = message.BlogatUser.Nick;
						}
						ws.Cells[row, col + 3].Value = message.Tel;
						ws.Cells[row, col + 4].Value = message.Text;
						ws.Cells[row, col + 5].Value = message.SubmittedAt.ToShortDateString();
						

						row++;
					}
					stream = new MemoryStream(p.GetAsByteArray());
				}
			}
			
			return File(stream.ToArray(), "application/vnd.ms-excel", "User messages.xls");
        }
    }
}

Blogat/Controllers/MessageController.cs
using Blogat.Models.Message;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blogat.Controllers
{
    public class MessageController : BaseController
    {
		[Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
			List<MessageModel> messages = new List<MessageModel>();
			MessageViewModel Model = new MessageViewModel();
			using (Context)
			{
				IEnumerable<DAL.Message> dalMessages = Context.MessageRepository.GetAll();
				foreach(var dalMessage in dalMessages)
				{
					MessageModel message = new MessageModel();

					message.Id = dalMessage.Id;

					message.SubmittedAt = dalMessage.SubmittedAt.ToLocalTime();
					message.Name = dalMessage.Name;

					if (dalMessage.UserId != null)
					{
						message.Email = dalMessage.BlogatUser.Email;
						message.Name = dalMessage.BlogatUser.Nick;

					}
					else
					{
						message.Email = dalMessage.Email;
						message.Name = dalMessage.Name;
						message.Tel = dalMessage.Tel;
					}

					messages.Add(message);
				}
			}
			Model.Messages = messages;
			return View(Model);
        }

		[Authorize(Roles = "Admin")]
		public ActionResult Display(int MessageId)
		{
			MessageModel Model = new MessageModel();
			using (Context)
			{
				DAL.Message dalMessage = Context.MessageRepository.FirstOrDefault(x => x.Id == MessageId);
				Model.Id = dalMessage.Id;

				Model.SubmittedAt = dalMessage.SubmittedAt.ToLocalTime();
				Model.Name = dalMessage.Name;
				Model.Text = dalMessage.Text;

				if (dalMessage.UserId != null)
				{
					Model.Email = dalMessage.BlogatUser.Email;
					Model.Name = dalMessage.BlogatUser.Nick;

				}
				else
				{
					Model.Email = dalMessage.Email;
					Model.Name = dalMessage.Name;
					Model.Tel = dalMessage.Tel;
				}
				
				
			}
			return View(Model);
		}
	}

	
}

Blogat/Views/Message/Display.cshtml
@using Blogat.Models.Message
@model MessageModel
@section Breadcrumb
{

  <i class="fas fa-greater-than"></i>
  @Html.ActionLink("Messages", "Index", "Message")
  <i class="fas fa-greater-than"></i>
  @Html.ActionLink("Message", "Display", new { MessageId = Model.Id })

  <div class="header">
    Message
  </div>
}
<!DOCTYPE html>

<html>
<head>
  <meta name="viewport" content="width=device-width" />
  <title>Index</title>
</head>
<body>
  <div class="blogat-panel">
    @Model.Text
  </div>
</body>
</html>

Blogat/Views/Message/Index.cshtml
@using Blogat.Models.Message
@model MessageViewModel
@section Breadcrumb
{

  <i class="fas fa-greater-than"></i>
  @Html.ActionLink("Messages", "Index", new { }, null)

  <div class="header">
    Messages
  </div>
}
<!DOCTYPE html>

<html>
<head>
  <meta name="viewport" content="width=device-width" />
  <title>Index</title>
</head>
<body>
  <div class="blogat-panel">

    <buttom class="blogat-export-button" onclick="document.location = '@Url.Action("AllMessages","Export")'">
      <i class="fas fa-file-excel"></i>
      <span class="menu-text">Export .xls</span>
    </buttom>
    <table>
      <th>Name</th>
      <th>Email</th>
      <th>Tel</th>
      <th></th>
      <th>Submitted At</th>
      @foreach (var message in Model.Messages)
	  {

        <tr class="message" onclick="document.location = '@Url.Action("Display", "Message", new { MessageId = message.Id})'">
          <td>@message.Name</td>
          <td>@message.Email</td>
          <td>@message.Tel</td>
          <td>@message.Text</td>
          <td>@message.SubmittedAt</td>
        </tr>
	  }
    </table>
  </div>
</body>
</html>