Blogat/Models/DashBoard/DashBoardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Blogat.Models.Shared;
using Blogat.Models.Topic;

namespace Blogat.Models.Dashboard
{
    public class DashboardViewModel
    {
        public List<TopicModel> Topics { get; set; }
		public string AllTags { get; set; }
        public PaginationModel Pagination { get; set; }
	}
}

Blogat/Models/Dashboard/EditTopicViewModel.cs
using Blogat.Models.Topic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Blogat.Models.Dashboard
{
	public class EditTopicViewModel
	{
		public TopicModel Topic { get; set; }
		public string AllTags { get; set; }
	}
}

Blogat/Models/Dashboard/RatingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Blogat.Models.Dashboard
{
	public class RatingModel
	{
		public int TopicId { get; set; }
		public double? Rating { get; set; }
	}
}

Blogat/Controllers/DashBoardController.cs
using System;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Blogat.Models.Dashboard;
using Blogat.Models.Topic;
using Common.Code;
using Common.Security;
using DAL;
using DAL.Extentions;
using DAL.UnitsOfWork;
using Common.Enums;
using Blogat.Commands.Dashboard;
using Blogat.Models.Shared;
using DAL.IRepository;

namespace Blogat.Controllers
{
	public class DashboardController : BaseController
	{
		[HttpGet]
		public ActionResult Index(int? PageNo, int PageSize = 5)
		{
			DashboardViewModel Model = new DashboardViewModel();
			List<TopicModel> Topics = new List<TopicModel>();
            PaginationModel Pagination = new PaginationModel();
            if (PageNo == null || PageNo < 1)
            {
                PageNo = 1;
            }
            Pagination.CurrentPage = (int)PageNo;
			using (Context)
			{
				bool IsAdmin = User.IsInRole("Admin");

				double AllTopicsCount = Context.TopicRepository.Count(
				   x => x.Status == (int)TopicStatus.Active || IsAdmin);

				Pagination.LastPage = (int)Math.Ceiling(AllTopicsCount / PageSize);
				if (Pagination.LastPage < Pagination.CurrentPage)
					Pagination.CurrentPage = Pagination.LastPage;


                IEnumerable<Topic> topics =
                    Context
                        .TopicRepository
						.OrderBy(x => x.Status)
						.ThenByDescending(x => x.CreatedAt)
						.GetPage(Pagination.CurrentPage, PageSize)
						.Where(x => x.Status == (int)TopicStatus.Active || IsAdmin);
                        

               

				Model.AllTags = getAllTags(Context);

				foreach (var topic in topics)
				{

                    Topics.Add(AutoMapper.Mapper.Map<TopicModel>(topic));
				}
			}

			Model.Topics = Topics;
			Model.Pagination = Pagination;

			return View(Model);
		}


		[HttpPost]
		[Authorize(Roles = "Admin")]
		public ActionResult Index(AddTopicCommand Command)
		{
            if (ModelState.IsValid)
            {

                DAL.Topic dalTopic = new Topic();
				dalTopic.Title = Command.Title;
				List<string> tagsList = new List<string>(Command.Tags.Split(','));

				IEnumerable<DAL.Tag> inputTags = tagsList.Select(x => 
				new DAL.Tag() { TagName = x}
				);

				
				using (Context)
				{
					var allTags = Context.TagRepository.GetAll();

					var existingDalTags = allTags.Where(x => tagsList.Exists(y => y == x.TagName)).ToList();
					int existingCount = existingDalTags.Count;
					var newDalTags = inputTags.Where(x =>
					    existingCount > 0 ? !existingDalTags.Exists(y => y.TagName == x.TagName) : true).ToList();

					existingDalTags.AddRange(newDalTags);

					
					Context.TopicRepository.Add(
						new Topic()
						{
							Title = Command.Title,
							Status = 0,
							Tag = existingDalTags,
							CreatedAt = DateTime.UtcNow
								
						}
						);

                }
            }
            


			return RedirectToAction("Index");
		}

		[HttpGet]
		[Authorize(Roles = "Admin")]
		public ActionResult Edit(int TopicId)
		{
			EditTopicViewModel Model = new EditTopicViewModel();
			using (Context)
			{
				DAL.Topic topic = Context.TopicRepository.Get(TopicId);
				Model.AllTags = getAllTags(Context);
				
				Model.Topic = new TopicModel()
					{
						Title = topic.Title,
						TopicId = topic.Id,
						Tags = topic.Tag.Select(x => x.TagName).OrderBy(x => x)
					};
				
			}
			

			return View(Model);
		}


		[HttpPost]
		[Authorize(Roles = "Admin")]
		public ActionResult Edit(EditTopicCommand Command)
        {
            if (ModelState.IsValid)
            {
				using (Context)
				{
					Topic dalTopic = Context.TopicRepository.Include(x => x.Tag).First(x => x.Id == Command.TopicId);
					dalTopic.Title = Command.Title;

					List<string> tagsList = new List<string>(Command.Tags.Split(','));

					IEnumerable<DAL.Tag> inputTags = tagsList.Select(x =>
					new DAL.Tag() { TagName = x }
					);


					var allTags = Context.TagRepository.GetAll();

					var existingDalTags = allTags.Where(x => tagsList.Exists(y => y == x.TagName)).ToList();
					int existingCount = existingDalTags.Count;
					var newDalTags = inputTags.Where(x =>
					 existingCount > 0 ? !existingDalTags.Exists(y => y.TagName == x.TagName) : true).ToList();

					existingDalTags.AddRange(newDalTags);
					dalTopic.Tag = existingDalTags;


                }
            }



            return RedirectToAction("Index");
		}

		[HttpPost]
		public JsonResult Rate(int TopicId, byte Rate)
		{
			if (!User.Identity.IsAuthenticated)
				return Json(new { status = HttpStatusCode.Unauthorized }, JsonRequestBehavior.DenyGet);
			if (Rate < 1 || Rate > 5)
				return Json(new { status = HttpStatusCode.Forbidden }, JsonRequestBehavior.DenyGet);
			using (Context)
			{
				DAL.Topic topic = Context.TopicRepository.FirstOrDefault(x => x.Id == TopicId);
				if (topic == null)
					return Json(new { status = HttpStatusCode.NotFound }, JsonRequestBehavior.DenyGet);

				int id = LoggedUser.Id;
				BlogatUser user = Context.BlogatUserRepository.Get(id);
				DAL.Rate existingRate = user.Rate.FirstOrDefault(x => x.TopicId == TopicId);
				if (existingRate == null)
				{

					Rate rate = new Rate();
					rate.UserId = id;
					rate.TopicId = TopicId;
					rate.TopicRating = Rate;
					user.Rate.Add(rate);
				}
				else
				{
					existingRate.TopicRating = Rate;
				}
				Context.Complete();
				double? avaregeRate = topic.GetAvaregeRate();
				return Json(new { status = HttpStatusCode.OK, value = avaregeRate }, JsonRequestBehavior.DenyGet);
			}
		}

		[HttpGet]
		public JsonResult GetRatings(int[] TopicsIds)
		{
			if(TopicsIds == null)
				return Json(new { status = HttpStatusCode.BadRequest }, JsonRequestBehavior.AllowGet);
			using (Context)
			{
				IEnumerable<DAL.Topic> topics = null;
				List<RatingModel> model = new List<RatingModel>();

				try
				{
					topics = Context.TopicRepository.GetAllByKeys(TopicsIds);
					foreach (Topic topic in topics)
					{
						model.Add(new RatingModel()
						{
							TopicId = topic.Id,
							Rating = topic.GetAvaregeRate()
						});
					}
				}
				catch (Exception e)
				{
					return Json(new { status = HttpStatusCode.NotFound }, JsonRequestBehavior.AllowGet);
				}
				if (topics == null)
					return Json(new { status = HttpStatusCode.NotFound }, JsonRequestBehavior.AllowGet);

				
				return Json(new { status = HttpStatusCode.OK, value = model.ToArray() }, JsonRequestBehavior.AllowGet);
			}
		}


		[HttpGet]
		public RedirectToRouteResult ToggleStatus(int TopicId)
		{
			using (Context)
			{
				DAL.Topic topic = Context.TopicRepository.FirstOrDefault(x => x.Id == TopicId);
				if(topic != null)
					topic.Status ^= 1;
				return RedirectToAction("Index");
			}
		}

		[HttpPost]
		[Authorize(Roles = "Admin,User")]
		public JsonResult CanRate(int TopicId)
		{
			using (Context)
			{
				int id = LoggedUser.Id;
				BlogatUser user = Context.BlogatUserRepository.Get(id);
				if (user.Rate.FirstOrDefault(x => x.TopicId == TopicId) != null)
				{

					return Json(HttpStatusCode.Conflict, JsonRequestBehavior.DenyGet);
				}

			}
			return Json(HttpStatusCode.OK, JsonRequestBehavior.DenyGet);



		}

		private string getAllTags(UnitOfWork Ctx)
		{

			return Ctx.TagRepository
				.GetAll()
				.Select(x => x.TagName)
				.Aggregate((x, y) => x + "," + y);
		}
	}
}

Blogat/Controllers/TopicController.cs
using Blogat.Commands.Topic;
using Blogat.Models.Post;
using Blogat.Models.Topic;
using Common.Code;
using Common.Enums;
using Common.Helpers;
using DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Blogat.Controllers
{
	public class TopicController : BaseController
    {
		[HttpGet]
		public ActionResult Index(int TopicId)
		{
			TopicViewModel Model = new TopicViewModel();
			Model.Posts = new List<PostModel>();
			List<DAL.Post> Posts;

			Model.TopicId = TopicId;
			using (Context)
			{
                bool IsAdmin = User.IsInRole("Admin");
				DAL.Topic Topic = Context.TopicRepository.FirstOrDefault(x => x.Id == TopicId &&
                (x.Status == (int)TopicStatus.Active || IsAdmin));
                Posts = Topic.Post.OrderByDescending(x => x.CreationDate.Date).ToList();

				
				Model.TopicTitle = Topic.Title;

				foreach (var dalPost in Posts)
				{
					List<CommentModel> comments = new List<CommentModel>();

					foreach (var dalComment in dalPost.Comment)
					{
						comments.Add(new CommentModel()
						{
							Author = dalComment.BlogatUser?.Nick ?? "User Deleted",
							CreatedAt = dalComment.CreatedAt,
							Text = dalComment.Text
						});

					}

					
					TagBuilder spoiler = new TagBuilder("a");
					spoiler.InnerHtml = "...(continue reading)";
					spoiler.Attributes.Add("href", Url.Action("Index", "Post", new { PostId = dalPost.Id }));
					

					string shortText = FormatHelper.ShortenText(dalPost.Text, Consts.PostPreviewLength, false);
					MvcHtmlString content;
					if (shortText.Length < dalPost.Text.Length)
					{
						content = new MvcHtmlString(shortText + spoiler);
					}
					else
					{
						content = new MvcHtmlString(shortText);
					}


					Model.Posts.Add(new PostModel()
					{
						PostId = dalPost.Id,
						Comments = comments,
						Content = content,
						PostedAt = dalPost.CreationDate,
						Title = dalPost.Title,
						Settings = new PostSettingsModel()
						{
							Mode = CommentsMode.ToggleDisabled
						}
					});

				}
			}


			return View(Model);
		}


		[HttpPost]
		[Authorize(Roles = "Admin")]
		public ActionResult Index(AddPostCommand Command)
		{
			DAL.Post dalPost = new Post();
			dalPost.CreationDate = DateTime.UtcNow;
			dalPost.Title = Command.PostTitle;
			dalPost.Text = Command.PostContent;

			using (Context)
			{
				DAL.Topic dalTopic = Context.TopicRepository.Get(Command.TopicId);
				dalTopic
					.Post
					.Add(dalPost);
			}


			return RedirectToAction("Index", new { Command.TopicId });
		}

		

	}

}

Blogat/Views/DashBoard/Index.cshtml
@using Blogat.Models.Dashboard;
@using Common.Enums;
@using System.Globalization;
@model DashboardViewModel
@{
  ViewBag.Title = "Main dashboard";
  bool IsAdmin = User.IsInRole("Admin");
}
@section Breadcrumb{
  <i class="fas fa-greater-than"></i>
  <div class="header">
    Dashboard
  </div>
}
<div id="urls" 
	 data-rate-url="@Url.Action("Rate","Dashboard")" 
	 data-get-ratings-url="@Url.Action("GetRatings","Dashboard")"
	 data-login-url="@Url.Action("Login","Account")">

</div>
@foreach (var topic in Model.Topics)
{
  double ratingValue = topic.Rating.HasValue ? topic.Rating.Value : 0;

  <div class="blogat-panel overflow-hidden @(topic.Status == TopicStatus.Active ? "" : "grayscale-filter" )">

    @if (IsAdmin)
	{
      <button type="button" class="blogat-edit-button" onclick="document.location = '@Url.Action("Edit","Dashboard",new { TopicId = topic.TopicId})'">Edit</button>
      <button type="button" class="blogat-delete-button" onclick="document.location = '@Url.Action("ToggleStatus","Dashboard",new { TopicId = topic.TopicId})'" title="@(topic.Status == TopicStatus.Active ? "Archive" : "Unarchive" )">
        <i class="far fa-eye@(topic.Status == TopicStatus.Active ? "-slash" : "" )"></i>
      </button>
	}
    <div class="display-block">
      <div class="display-inline-block  padding-right-1">
        <div class="topic-head">Latest Activity </div>
        <div>
          @topic.LeatestActivity
        </div>
      </div>
      <div class="display-inline-block">
        <div class="topic-head">Title</div>
        <div>
          <a href="@Url.Action("Index","Topic", new { TopicId = topic.TopicId})">@topic.Title</a>
        </div>
      </div>
      <div class="display-inline-block float-right">
        <div class="topic-head text-right">Rating</div>
        <div class="topic-rating" data-topic-id="@topic.TopicId">
          <img src="@Url.Content("~/Content/loader2.svg")" class="loader hide">
          <div class="topic-rating-star">
            <i class="fa@(ratingValue >= 0.5 ? "s" : "r") fa-star@(ratingValue >= 0.5 && ratingValue < 1 ? "-half-alt" : "")"></i>
          </div>
          <div class="topic-rating-star">
            <i class="fa@(ratingValue >= 1.5 ? "s" : "r") fa-star@(ratingValue >= 1.5 && ratingValue < 2 ? "-half-alt" : "")"></i>
          </div>
          <div class="topic-rating-star">
            <i class="fa@(ratingValue >= 2.5 ? "s" : "r") fa-star@(ratingValue >= 2.5 && ratingValue < 3 ? "-half-alt" : "")"></i>
          </div>
          <div class="topic-rating-star">
            <i class="fa@(ratingValue >= 3.5 ? "s" : "r") fa-star@(ratingValue >= 3.5 && ratingValue < 4 ? "-half-alt" : "")"></i>
          </div>
          <div class="topic-rating-star">
            <i class="fa@(ratingValue >= 4.5 ? "s" : "r") fa-star@(ratingValue >= 4.5 && ratingValue < 5 ? "-half-alt" : "")"></i>
          </div>
          <span class="rating-value">
            @(ratingValue.ToString("0.0", CultureInfo.InvariantCulture))
          </span>
        </div>
      </div>
    </div>
    <div>
      @if (topic.Tags.Count() > 0)
	  {
        <span class="topic-head">Tags:</span>
		foreach (var tag in topic.Tags)
		{
          <div class="tag"><span class="tag-text"><i class="fas fa-hashtag"></i>@tag</span></div>
		}
	  }
    </div>
  </div>

}

<div class="blogat-pagination">
  <div class="blogat-pagination-previous">
    @if (Model.Pagination.CurrentPage > 1)
	{
	  int prevPage = Model.Pagination.CurrentPage - 1;
      @Html.ActionLink("prev", "Index", new { PageNo = prevPage })
	}
	else
	{
      <span class="blogat-pagination-disabled" title="Not available">prev</span>
	}
  </div>
  <div class="blogat-pagination-current">
    @Model.Pagination.CurrentPage
  </div>
  <div class="blogat-pagination-next">
    @if (Model.Pagination.LastPage > Model.Pagination.CurrentPage)
	{
	  int nextPage = Model.Pagination.CurrentPage + 1;
      @Html.ActionLink("next", "Index", new { PageNo = nextPage })
	}
	else
	{
      <span class="blogat-pagination-disabled" title="Not available">next</span>
	}
  </div>
</div>
@if (IsAdmin)
{
  using (Html.BeginForm("Index", "Dashboard", FormMethod.Post, new { onSubmit = "return onTopicSubmit();" }))
  {
    <div class="blogat-panel">
      <div class="topic-head">New topic</div>
      <label>
        <label for="Title">Title</label>
        <input type="text" name="Title" />
      </label>
      <div id="tag-list"></div>
      Type in tags, separated by commas.
      @Html.Hidden("Tags", null, new { id = "tags-hidden" })
      <label>
        <input type="text" class="tag-input" />
      </label>

      <input type="submit" value="Submit" />
    </div>
  }
  <div id="all-tags" class="hide">@Model.AllTags</div>
}