Blogat/Models/Shared/PaginationModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Blogat.Models.Shared
{
    public class PaginationModel
    {
        public int CurrentPage { get; set; }
        public int LastPage { get; set; }
    }
}

Blogat/Controllers/AboutController.cs
using Blogat.Commands.About;
using Blogat.Models.About;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blogat.Controllers
{
    public class AboutController : BaseController
	{
		[HttpGet]
		public ActionResult Index()
        {
			AboutModel Model = new AboutModel();
			using (Context)
			{

				Model.Text = Context.AboutMeRepository.FirstOrDefault(x => true)?.Text;

			}

            return View(Model);
        }

		[HttpGet]
		public ActionResult Edit()
		{
			AboutModel Model = new AboutModel();
			using (Context)
			{

				Model.Text = Context.AboutMeRepository.FirstOrDefault(x => true)?.Text;

			}

			return View(Model);
		}

		[HttpPost]
		public RedirectToRouteResult Edit(EditAboutCommand Command)
		{
            if(ModelState.IsValid)
            {

                using (Context)
                {

                    Context.AboutMeRepository.FirstOrDefault(x => true).Text = Command.Text;

                }
            }

			return RedirectToAction("Index");
		}


	}
}

Blogat/Controllers/ContactController.cs
using Blogat.Commands.Contact;
using DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blogat.Controllers
{
    public class ContactController : BaseController
	{

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
		public ActionResult Index(AddMessageCommand Command)
        {
            if (ModelState.IsValid)
            {

                DAL.Message guestMessage = new Message()
                {
                    Name = Command.Name,
                    Email = Command.Email,
                    Text = Command.Message,
                    SubmittedAt = DateTime.UtcNow,
                    Tel = Command.Tel,
                    UserId = IsAuthenticated ? (int?)LoggedUser.Id : null
                };

                using (Context)
                {
                    Context.MessageRepository.Add(guestMessage);
                }
            }
			return RedirectToAction("Index");
		}

	}
}

Blogat/Controllers/MessageController.cs
using Blogat.Models.Message;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blogat.Controllers
{
    public class MessageController : BaseController
    {
		[Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
			List<MessageModel> messages = new List<MessageModel>();
			MessageViewModel Model = new MessageViewModel();
			using (Context)
			{
				IEnumerable<DAL.Message> dalMessages = Context.MessageRepository.GetAll();
				foreach(var dalMessage in dalMessages)
				{
					MessageModel message = new MessageModel();

					message.Id = dalMessage.Id;

					message.SubmittedAt = dalMessage.SubmittedAt.ToLocalTime();
					message.Name = dalMessage.Name;

					if (dalMessage.UserId != null)
					{
						message.Email = dalMessage.BlogatUser.Email;
						message.Name = dalMessage.BlogatUser.Nick;

					}
					else
					{
						message.Email = dalMessage.Email;
						message.Name = dalMessage.Name;
						message.Tel = dalMessage.Tel;
					}

					messages.Add(message);
				}
			}
			Model.Messages = messages;
			return View(Model);
        }

		[Authorize(Roles = "Admin")]
		public ActionResult Display(int MessageId)
		{
			MessageModel Model = new MessageModel();
			using (Context)
			{
				DAL.Message dalMessage = Context.MessageRepository.FirstOrDefault(x => x.Id == MessageId);
				Model.Id = dalMessage.Id;

				Model.SubmittedAt = dalMessage.SubmittedAt.ToLocalTime();
				Model.Name = dalMessage.Name;
				Model.Text = dalMessage.Text;

				if (dalMessage.UserId != null)
				{
					Model.Email = dalMessage.BlogatUser.Email;
					Model.Name = dalMessage.BlogatUser.Nick;

				}
				else
				{
					Model.Email = dalMessage.Email;
					Model.Name = dalMessage.Name;
					Model.Tel = dalMessage.Tel;
				}
				
				
			}
			return View(Model);
		}
	}

	
}

Blogat/Controllers/PostController.cs
using Blogat.Commands.Post;
using Blogat.Models.Post;
using Common.Enums;
using DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blogat.Controllers
{
	public class PostController : BaseController
	{
		[HttpGet]
		public ActionResult Index(int PostId)
		{
			PostViewModel Model = GetPostViewModelById(PostId);

			return View(Model);
        }


		[HttpGet]
		[Authorize(Roles = "Admin")]
		public ActionResult Edit(int PostId)
		{
			PostViewModel Model = GetPostViewModelById(PostId);

			return View(Model);
		}

		[HttpPost]
		[Authorize(Roles = "Admin")]
		public ActionResult Edit(EditPostCommand Command)
		{
            if(ModelState.IsValid)
            {

			    using (Context)
			    {
				    Post dalPost = Context.PostRepository.Get(Command.PostId);
				    dalPost.Title = Command.PostTitle;
				    dalPost.Text = Command.PostContent;
			    }

            }
            return RedirectToAction("Index", new { Command.PostId });
		}


		[HttpPost]
		[Authorize(Roles = "User,Admin")]
		public ActionResult AddComment(AddCommentCommand Command)
        {
            if (ModelState.IsValid)
            {
                DAL.Comment dalComment = new Comment();
                dalComment.CreatedAt = DateTime.UtcNow;
                dalComment.Text = Command.CommentContent;

                using (Context)
                {

                    int? authorId = Context.BlogatUserRepository.FirstOrDefault(x => x.Id == LoggedUser.Id)?.Id;
                    dalComment.AuthorId = authorId;

                    DAL.Post dalPost = Context.PostRepository.Get(Command.PostId);
                    dalPost
                        .Comment
                        .Add(dalComment);
                }
            }


			return RedirectToAction("Index", new { Command.PostId });
		}

		private PostViewModel GetPostViewModelById(int Id)
		{
			PostModel Post = new PostModel();
			PostViewModel Model = new PostViewModel();
			using (Context)
            {
                bool IsAdmin = User.IsInRole("Admin");
                Post dalPost = Context.PostRepository.FirstOrDefault(x => x.Id == Id &&
                (x.Topic.Status == (int)TopicStatus.Active || IsAdmin));
				List<CommentModel> comments = new List<CommentModel>();

				foreach (var dalComment in dalPost.Comment)
				{
					comments.Add(new CommentModel()
					{
						Author = dalComment.BlogatUser?.Nick ?? "Deleted user",
						CreatedAt = dalComment.CreatedAt,
						Text = dalComment.Text
					});

				}

				Model.TopicId = dalPost.TopicId;
				Model.TopicTitle = dalPost.Topic.Title;
				Post.PostId = dalPost.Id;
				Post.Comments = comments;
				Post.Content = new MvcHtmlString(dalPost.Text);
				Post.PostedAt = dalPost.CreationDate;
				Post.Title = dalPost.Title;
				Post.Settings = new PostSettingsModel()
				{
					Mode = CommentsMode.ToggleEnabled,
					IsEditable = true

				};
			}

			Model.Post = Post;

			return Model;
		}

	}
}

Blogat/Views/Shared/AccountLayout.cshtml
<!DOCTYPE html>

<html>
<head>
  <meta name="viewport" content="width=device-width" />
  <title>@ViewBag.Title</title>
  @Styles.Render("~/foundation/styles")
  @Styles.Render("~/custom/styles")
  <link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">
  <style>
	body{
	  background:none;
	}
  </style>
</head>
<body>
  <div class="grid-y">
    <div class="grid-x account-content margin-top-3">

      <div class="cell text-justify">

        <div class="row callout primary padding-2">
          @RenderBody()
        </div>
      </div>
    </div>
  </div>

  @RenderSection("scripts", required: false)

</body>
</html>

Blogat/Views/Shared/PostPartial.cshtml
@using Common.Enums;
@using Blogat.Models.Post;
@using Common.Security;
@model PostModel
@{

	bool IsAdmin = HttpContext.Current.User.IsInRole("Admin");
	bool IsAuthenticated = HttpContext.Current.User.Identity.IsAuthenticated;
	string CommentIconClass;
	int? CommentsCount = Model.Comments?.Count;
	switch (CommentsCount)
	{

	  case null:
		CommentIconClass = null;
		break;
	  case 0:
		CommentIconClass = "fas fa-plus";
		break;
	  case 1:
		CommentIconClass = "far fa-comment";
		break;
	  default:
		CommentIconClass = "far fa-comments";
		break;
	}
	string PostLink = Model.Settings.Mode == CommentsMode.ToggleDisabled ? Url.Action("Index", "Post", new { PostId = Model.PostId }) : "";
	string commentDescriptor = (CommentsCount == 0 ? "No" : CommentsCount.ToString()) + " comment" + (CommentsCount == 1 ? "" : "s");
}
<style>
</style>
<div data-location="@Url.Action("Index", "Post", new { PostId = Model.PostId })" class="blogat-panel">


  @if (IsAdmin && Model.Settings.IsEditable)
  {
    <button type="button" class="blogat-edit-button" onclick="document.location = '@Url.Action("Edit", new { Model.PostId})'">Edit</button>
  }

  @if (Model.PostedAt.HasValue)
  {
    <div class="blogat-panel-heading">
      @Model.Title
      <span class="post-date">
        @(((DateTime)Model.PostedAt).ToShortDateString())
      </span>
    </div>
  }

  @if (!string.IsNullOrEmpty(Model.Content.ToString()))
  {
    <div class="blogat-panel-text">
      @Model.Content
    </div>
  }

  @if (Model.Settings.Mode != CommentsMode.HideCommands)
  {
    <div class="comments-container">
      @if (Model.Settings.Mode != CommentsMode.CommentsDisabled)
	  {
        <div class="comments-descriptor noselect">
          <i class="@CommentIconClass"></i>
          @commentDescriptor


        </div>
		if (Model.Settings.Mode == CommentsMode.ToggleEnabled)
		{
          <div class="comments-list">

            @foreach (var comment in Model.Comments)
			{
              <div class="comment-container">
                <div class="comment-header">
                  @comment.Author
                  <div class="comment-date">
                    @(((DateTime)comment.CreatedAt).ToShortDateString())
                  </div>
                </div>
                <div class="comment-text">
                  @comment.Text
                </div>
                <div class="display-inline-block float-right">
                </div>
              </div>
			}
            @if (IsAuthenticated)
			{

			  using (Html.BeginForm("AddComment", "Post", FormMethod.Post, null))
			  {

                <label>
                  New Comment:
                  @(Model.Content = new MvcHtmlString(""))
                  <textarea name="CommentContent"></textarea>
                  @Html.HiddenFor(x => x.PostId)
                  <input type="text" class="hide" value="1" />
                </label>
                <input type="submit" value="Submit" />
			  }
			}
			else
			{
              <table>
                <tr>
                  <td>
                    <span class="comment-auth-info-icon">
                      <i class="fas fa-info-circle"></i>
                    </span>
                  </td>
                  <td class="width-100">
                    <span class="comment-auth-info ">
                      @if ((CommentsCount ?? 0) > 0)
					  {
                        <span>If you want to participate in this disscussion,</span>
					  }
					  else
					  {

                        <span>For this to work,</span>
					  }
                      <span>you need to</span>
                      <a href="@Url.Action("Login","Account")">Log In</a>.

                      <br>
                      Not yet a Blogat member? <a href="@Url.Action("Register","Account")">Join us!</a>.

                    </span>

                  </td>

                </tr>

              </table>
			}

          </div>
		}
	  }
	  else
	  {
        <i class="fas fa-comment-slash">Comments disabled</i>

	  }


    </div>
  }
</div>

Blogat/Views/Shared/_Layout.cshtml
@using Common.Security;
@using Common.Helpers;
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>@ViewBag.Title</title>
  @Styles.Render("~/foundation/styles")
  @Styles.Render("~/custom/styles")
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>
@{
	BlogatIdentity User = HttpContext.Current.User.Identity as BlogatIdentity;
	object header = "";
	TempData.TryGetValue("header", out header);
}

<body>
  <div class="grid-container blogat-container">
    <div class="grid-x">
      <div class="cell small-10 float-center">

        <div class="grid-x">
          <div class="cell small-12 text-center medium-text-left float-center">
            <a id="logo" href="@Url.Action("Index","Home")">
              BLOG<span id="at">@@</span>
            </a>
          </div>
        </div>
        <div class="padding-1 breadcrumb">
          <a href="@Url.Action("Index","Home")">
            <i class="fas fa-home"></i>
          </a>
          @RenderSection("Breadcrumb", false)
        </div>
        <div class="grid-x margin-top-1">
          <div class="cell hide-for-small-only medium-4 large-3">
            <div class="blogat-panel">
              <a href="@Url.Action("Index","Dashboard")">
                <div class="menu-item">
                  <div class="menu-item-inner">
                    <i class="fas fa-bars"></i>
                    <span class="menu-text">Dashboard</span>
                  </div>
                </div>
              </a>
              @if (HttpContext.Current.User.IsInRole("Admin"))
			  {
				  <a href="@Url.Action("Index","Message")">
					<div class="menu-item">
					  <div class="menu-item-inner">
						<i class="far fa-envelope"></i>
						<span class="menu-text">Messages</span>
					  </div>
					</div>
				  </a>
			  }
			  else
			  {
                <a href="@Url.Action("Index","Contact")">
                  <div class="menu-item">
                    <div class="menu-item-inner">
                      <i class="fas fa-phone-volume"></i>
                      <span class="menu-text">Contact</span>
                    </div>
                  </div>
                </a>
			  }
              <a href="@Url.Action("Index","About")">
                <div class="menu-item">
                  <div class="menu-item-inner">
                    <i class="fas fa-user"></i>
                    <span class="menu-text">About</span>
                  </div>
                </div>
              </a>
              @if (User?.IsAuthenticated ?? false)
			  {
                <a href="@Url.Action("Logout","Account")">
                  <div class="menu-item">
                    <div class="menu-item-inner">
                      <i class="fas fa-sign-out-alt"></i>
                      <span class="menu-text">Log Out</span>
                    </div>
                  </div>
                </a>
			  }
			  else
			  {
                <a href="@Url.Action("Login","Account")">
                  <div class="menu-item">
                    <div class="menu-item-inner">
                      <i class="fas fa-sign-in-alt"></i>
                      <span class="menu-text">Log In</span>
                    </div>
                  </div>
                </a>
                <a href="@Url.Action("Register","Account")">
                  <div class="menu-item">
                    <div class="menu-item-inner">
                      <i class="fas fa-feather-alt"></i>
                      <span class="menu-text">Register</span>
                    </div>
                  </div>
                </a>
			  }

            </div>

            <!--    <div class="blogat-panel">
			<span class="padding-0"><i class="fas fa-cookie-bite"></i> </span>
			<span>Blogat uses cookies to store your personal data.</span>

		  </div>-->
          </div>
          <div class="cell small-12 medium-8 large-9">
            <div class="margin-horizontal-2">
              @RenderBody()
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
  <footer>

      <span>&#9400; @DateTime.UtcNow.Year Blogat</span>
  </footer>
    @Scripts.Render("~/foundation/scripts")
    @Scripts.Render("~/custom/scripts")

    <script>
	  $(document).foundation();
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>